name: Security Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Scan for secrets
        run: |
          if grep -Ri "password" . --exclude=security.yml --exclude=docs.yml --exclude-dir=docs; then
            echo "Found risky word"
            exit 1
          else
            echo "Clean"
          fi
